### PR TITLE
Added CSS to terminate vertical lines

### PR DESCRIPTION
**Pull request by berge472**
I updated the style sheet to terminate the vertical Guidelines at the last node in each branch

image

### CODE REVIEW

**Comment by geekhybrid** [comment]
Lovely.

**Review by geekhybrid — COMMENTED** [review]
I am happy to approve and get merged. Please review the diffs due to white space changes. I'll create a linter for the project soon. 🔥👏👏

**Review by berge472 — COMMENTED** [review]
I added some comments and cleaned up whitespace/dead code

**Review by geekhybrid — APPROVED** [review]
Thanks!!

**Comment by geekhybrid** [comment]
Hi, @berge472 can you please have a look at the left border?

**Before**
image

**After**
image

**Comment by berge472** [comment]
I pushed a change that should fix this. I am having a hard time testing
though. Normally when I work on a package I can use 'npm link
../project/path' to use the local version while I develop, but when I do
that with this package I get the error "resolveComponent can only be used
in render() or setup().". Is there something I need to do when I build to
allow it to be linked?

**Comment by geekhybrid** [comment]
Thanks for looking at this.

You can run npm run serve on the project. It starts up a project that has HMR and uses the current state of the code. Hope it helps.

**Pull request merged**
